# Configure TypeScript Linting

root: true
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
plugins:
  - '@typescript-eslint'
  - 'eslint-plugin-tsdoc'
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
rules:
  tsdoc/syntax:
    - error
